swagger: "3.0.3"
info:
  version: "1.0.0"
  title: "API Documentation"
  description: "This is a sample API documentation using Swagger"
basePath: "/api"
schemes:
  - "http"
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: "Register a new user"
      description: "Endpoint to register a new user."
      parameters:
        - name: "user"
          in: "body"
          description: "User object that needs to be added"
          required: true
          schema:
            $ref: "#/definitions/RegisterRequest"
      responses:
        "200":
          description: Đăng ký thành công
        "409":
          description: Tải khoản đã tồn tại trong hệ thống
        "400":
          description: Bad request, invalid input
  /auth/login:
    post:
      tags:
        - Auth
      summary: "Log in user"
      description: "Endpoint to log in an existing user."
      parameters:
        - name: "user"
          in: "body"
          description: "User object that needs to be added"
          required: true
          schema:
            $ref: "#/definitions/LoginRequest"
          examples:
            example1:
              value:
                email: "admin@gmail.com"
                password: "password"
      responses:
        "200":
          description: Đăng nhập thành công
        "401":
          description: Sai mật khẩu
        "404":
          description: Tài khoản chưa đăng ký
        "500":
          description: Lỗi server
  /auth/logout:
    post:
      tags:
        - Auth
      summary: "Logout user"
      description: "Endpoint to log out an existing user."
      parameters:
        - name: "user log out"
          description: "User log out"
          required: true
          schema:
            $ref: "#/definitions/LoginRequest"
      responses:
        "200":
          description: "Đăng xuất thành công"
        "401":
          description: "Chưa đăng nhập hoặc phiên làm việc hết hạn"
  /auth/refresh-token:
    post:
      tags:
        - Auth
      summary: "refresh token"
      description: "Endpoint to refresh token an existing user."
      parameters:
        - name: "refresh token"
          in: "body"
          description: "refresh token"
          required: true
          schema:
            $ref: "#/definitions/RefreshTokenRequest"
      responses:
        "200":
          description: "Trả về accessToken"
        "401":
          description: "Unauthorized"
  /user/{id}:
    get:
      tags:
        - User
      summary: "Get user"
      description: "Endpoint to log out an existing user."
      parameters:
        - name: "id"
          in: "path"
          description: "Get User"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "Lấy thông tin user thành công"
          content:
            application/json:
              schema:
                $ref: "#/definitions/UserRequest"
        "401":
          description: "Chưa đăng nhập hoặc phiên làm việc hết hạn"
        "404":
          description: "User not found"
    patch:
      tags:
        - User
      summary: "Update User"
      description: "End point Create new User"
      parameters:
        - name: "id"
          in: "path"
          description: "User object that needs to be update"
          required: true
          schema:
            $ref: "#/definitions/UserRequest"
        - name: "User update"
          in: "body"
          description: "User object needs update"
          required: true
          schema:
            $ref: "#/definitions/UserRequest"
      responses:
        '200':
          description: Cập nhật thành công
        '400':
          description: Bad request, invalid input

    delete:
      tags:
        - User
      summary: Xoá user"
      description: "Endpoint to delete an existing user."
      parameters:
        - name: id
          in: path
          description: "ID of the user to delete"
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: "User đã được xoá thành công"
        "401":
          description: "Không có quyền xoá người dùng"
        "404":
          description: "User not found."
  /user/:
    post:
      tags:
        - User
      summary: "Post user"
      description: "Endpoint to log out an existing user."
      parameters:
        - name: "Post User"
          in: "body"
          description: "Post User"
          required: true
          schema:
            $ref: "#/definitions/UserRequest"
      responses:
        "200":
          description: "Tạo mới user thành công"
        "401":
          description: "Không có quyền tạo người dùng mới"
    
    get:
      tags:
        - User
      summary: "Get all User"
      description: "End point Get all categories"
      parameters:
        - name: "Get All User"
          # in: "body"
          description: "Get all User"
          required: false
          schema:
            $ref: "#/definitions/UserRequest"
      responses:
        '200':
          description: "Get All User Success"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/UserRequest"
        '401': 
          description: "Không có quyền get all user"
        '400':
          description: "not found"
    
definitions:
  RegisterRequest:
    type: object
    required:
      - username
      - email
      - password
    properties:
      username:
        type: string
      email:
        type: string
        format: email
      password:
        type: string
        format: password
  LoginRequest:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        format: email
      password:
        type: string
        format: password
  UserRequest:
    type: object
    required:
      - username
      - email
      - password
      - imgUrl
    properties:
      username:
        type: string
      email:
        type: string
        format: email
      password:
        type: string
        format: password
      imgUrl:
        type: string
  RefreshTokenRequest:
    type: object
    required:
      - refreshToken
    properties:
      refreshToken:
        type: string 
