export enum Roles {
  ADMIN = 1,
  USER = 2
}

export enum PermissionType {
  ADMIN = 'admin',
  ARTICLE_VIEW = 'article_view',
  ARTICLE_CREATE = 'article_create',
  ARTICLE_EDIT = 'article_edit',
  ARTICLE_DELETE = 'article_delete',
  CATEGORY_VIEW = 'category_view',
  CATEGORY_CREATE = 'category_create',
  CATEGORY_EDIT = 'category_edit',
  CATEGORY_DELETE = 'category_delete',
  USER_VIEW = 'user_view',
  USER_CREATE = 'user_create',
  USER_EDIT = 'user_edit',
  USER_DELETE = 'user_delete',
  MEDIA_UPLOAD = 'media_upload',
  MEDIA_DELETE = 'media_delete',
  COMMENT_APPROVE = 'comment_approve',
  COMMENT_VIEW = 'comment_view',
  COMMENT_CREATE = 'comment_create',
  COMMENT_EDIT = 'comment_edit',
  COMMENT_DELETE = 'comment_delete',
  ARTICLE_PUBLISH = 'article_publish',
  ARTICLE_SAVE_DRAFT = 'article_save_draft',
  ARTICLE_REPOST = 'article_repost',
  ARTICLE_HIDE = 'article_hide',
  TAG_VIEW = 'tag_view',
  TAG_CREATE = 'tag_create',
  TAG_EDIT = 'tag_edit',
  TAG_DELETE = 'tag_delete',
  REPORT_VIEW = 'report_view',
  SEO_VIEW = 'seo_view',
  SEO_EDIT = 'seo_edit'
}

export const permissions: string[] = [
  PermissionType.ADMIN,
  PermissionType.ARTICLE_VIEW,
  PermissionType.ARTICLE_CREATE,
  PermissionType.ARTICLE_EDIT,
  PermissionType.ARTICLE_DELETE,
  PermissionType.CATEGORY_VIEW,
  PermissionType.CATEGORY_CREATE,
  PermissionType.CATEGORY_EDIT,
  PermissionType.CATEGORY_DELETE,
  PermissionType.USER_VIEW,
  PermissionType.USER_CREATE,
  PermissionType.USER_EDIT,
  PermissionType.USER_DELETE,
  PermissionType.MEDIA_UPLOAD,
  PermissionType.MEDIA_DELETE,
  PermissionType.COMMENT_APPROVE,
  PermissionType.COMMENT_DELETE,
  PermissionType.COMMENT_VIEW,
  PermissionType.COMMENT_EDIT,
  PermissionType.COMMENT_CREATE,
  PermissionType.ARTICLE_PUBLISH,
  PermissionType.ARTICLE_SAVE_DRAFT,
  PermissionType.ARTICLE_REPOST,
  PermissionType.ARTICLE_HIDE,
  PermissionType.TAG_VIEW,
  PermissionType.TAG_CREATE,
  PermissionType.TAG_EDIT,
  PermissionType.TAG_DELETE,
  PermissionType.REPORT_VIEW,
  PermissionType.SEO_VIEW,
  PermissionType.SEO_EDIT
];
